version: "3.8"

services:
  # PHP-FPM Service
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_DATABASE=dressesl_shop
      - DB_USERNAME=your_user
      - DB_PASSWORD=your_password
    networks:
      - application
    depends_on:
      - db

  # MySQL Database Service
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: dressesl_shop
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - application

  # Nginx Web Server Service
  webserver:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - application

# Networks and Volumes
networks:
  application:
    driver: bridge

volumes:
  db_data:
