services:
  app:
    build: .
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=dressesl_shop
      - DB_USERNAME=your_user
      - DB_PASSWORD=your_password
    depends_on:
      - db
    ports:
      - 9000:9000
    networks:
      - application
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        composer install
        php artisan migrate
        php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: dressesl_shop
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - application

networks:
  application:
    driver: bridge

volumes:
  db_data:
